;Include file created by h2inc+ version C.2.0 on (UTC) 15/06/2024 16:37:44
;(C) G. Friedrich April 2024
;Source file: d:\objasm\projects\x\h2inc+\h\um_10.0.22621.0\mprapidef.h
;             Created on (UTC) 22/05/2024 17:57:07
;             Last modified on (UTC) 16/12/2023 11:05:36

ifndef _MPRAPIDEF_
  _MPRAPIDEF_ equ <>
  include lmcons.inc
  MAX_INTERFACE_NAME_LEN equ 256
  MAX_TRANSPORT_NAME_LEN equ 40
  MAX_MEDIA_NAME equ 16
  MAX_PORT_NAME equ 16
  MAX_DEVICE_NAME equ 128
  MAX_PHONE_NUMBER_LEN equ 128
  MAX_DEVICETYPE_NAME equ 16
endif
