; ==================================================================================================
; Title:      Real8Vector.inc
; Author:     G. Friedrich
; Version:    C.1.0
; Purpose:    ObjAsm support of Real8Vector objects.
; Notes:      Version C.1.0, February 2024
;               - First release.
; ==================================================================================================


TVectorName         textequ   <Real8Vector>
TVectorID           textequ   <Real8VectorID>
TVEC_ITEM_TYPE      textequ   <REAL8>

include .\TVector.inc                                   ;Template file