; ==================================================================================================
; Title:      NUI_Template_Shared.inc
; Author:     G. Friedrich
; Notes:      See QueryCpuStruct.asm
; ==================================================================================================


;General information
APP_TITLE                     textequ   <QueryCpuStruct Test Application>
ABOUT_TEXT                    textequ   <QueryCpuStruct Test Application>
COPYRIGHT                     textequ   <G. Friedrich   May 2026> 
VER_FILEVERSION               equ       1,0,0,0
VER_FILEVERSION_STR           textequ   <1.0>
VER_PRODUCTVERSION            equ       1,0,0,0
VER_PRODUCTVERSION_STR        equ       <1.0>

;Build information - updated automatically -
BUILD_NUMBER                  equ       15
BUILD_DATE_STR                textequ   <2026-07-12>
BUILD_BITNESS                 equ       64
BUILD_MODE                    equ       RLS


BUILD_BIN_FORMAT              equ       EXE
BUILD_BIN_SUFFIX_STR          textequ   <>
