; ==================================================================================================
; Title:      CAStr_CRLF_X.inc
; Author:     G. Friedrich
; Version:    C.1.0
; Notes:      Version C.1.0, October 2017
;               - First release.
; ==================================================================================================


.const
align ALIGN_DATA
bCRLF  BYTE  13, 10, 0
