; ==================================================================================================
; Title:      CAStr_Error_X.inc
; Author:     G. Friedrich
; Version:    C.1.0
; Notes:      Version C.1.0, October 2017
;               - First release.
; ==================================================================================================


.const
align ALIGN_DATA
bError  BYTE  "E", "r", "r", "o", "r", 0
