; ==================================================================================================
; Title:      CompressSignatures.inc
; Author:     G. Friedrich
; Version:    C.1.0
; Purpose:    Shared file defining compression signatures.
; Notes:      Version C.1.0, October 2023
;               - First release.
; ==================================================================================================


; Signatures
HEADER_MSZIP  equ 'PZSM'    ;'MSZP'
HEADER_XPRESS equ 'SRPX'    ;'XPRS'
HEADER_HUFF   equ 'FFUH'    ;'HUFF'
HEADER_LZMS   equ 'SMZL'    ;'LZMS'
