; ==================================================================================================
; Title:      LuaHost_Globals.inc
; Author:     G. Friedrich
; Version:    See LuaHost.asm
; Purpose:    ObjAsm LuaHost Application.
; ==================================================================================================


;General information
APP_TITLE                     textequ   <LuaHost Demonstration>
ABOUT_TEXT                    textequ   <LuaHost Demonstration>
COPYRIGHT                     textequ   <G. Friedrich   December 2023> 
VER_FILEVERSION               equ       1,0,0,0
VER_FILEVERSION_STR           textequ   <1.0>
VER_PRODUCTVERSION            equ       1,0,0,0
VER_PRODUCTVERSION_STR        textequ   <1.0>

;Build information - updated automatically -
BUILD_NUMBER                  equ       52
BUILD_DATE_STR                textequ   <2024-01-03>
BUILD_BITNESS                 equ       32
BUILD_MODE                    equ       RLS
BUILD_BIN_FORMAT              equ       EXE
BUILD_BIN_SUFFIX_STR          textequ   <>
