; ==================================================================================================
; Title:      ResGuard.inc
; Author:     G. Friedrich
; Version:    C.1.0
; Purpose:    Detection of resource leakages using ObjAsm ResGuard.dll.
; Notes:      Version C.1.0, August 2023
;               - First release.
; ==================================================================================================


ResGuardInit  proto :ptr
ResGuardStart proto
ResGuardStop  proto
ResGuardShow  proto

