;Include file created by h2inc+ version C.2.0 on (UTC) 19/05/2024 07:52:23
;(C) G. Friedrich April 2024
;Source file: d:\objasm\projects\x\h2inc+\h\masterinclude.h\masterinclude.h
;             Created on (UTC) 06/04/2024 06:16:29
;             Last modified on (UTC) 06/04/2024 06:18:18

include Windows.inc
include CommCtrl.inc
include commdlg.inc
include ShlObj.inc
include Shlwapi.inc
include PathCch.inc
include Richedit.inc
include Uxtheme.inc
include StdIO.inc
include WinSock2.inc
include sphelper.inc
include Tlhelp32.inc
include vsstyle.inc
include DbgHelp.inc
include d3d12.inc
include d3d9.inc
include d3d9caps.inc
include d3d9helper.inc
include d3d9types.inc
include d3dx9.inc
include d3dx9anim.inc
include d3dx9core.inc
include d3dx9effect.inc
include d3dx9math.inc
include d3dx9mesh.inc
include d3dx9shader.inc
include d3dx9shape.inc
include d3dx9tex.inc
include d3dx9xof.inc
include DSound.inc
include GdiPlus.inc
include ddrawi.inc
include vfw.inc
include IImgCtx.inc
include compressapi.inc
include ActivScp.inc
include ActivDbg.inc
include SetupAPI.inc
include http.inc
include sspi.inc
include winhttp.inc
